{
 "title": "F1 Anomaly Detection Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"car_telemetry\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"car_telemetry\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\" or r[\"_field\"] == \"is_anomaly\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r[\"is_anomaly\"] == 1)\r\n  |> keep(columns: [\"_time\", \"speed\"])\r\n  |> rename(columns: {speed: \"_value\"})\r\n  |> set(key: \"_field\", value: \"anomaly_speed\")"
    }
   ]
  },
  {
   "title": "Engine RPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"car_telemetry\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rpm\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"car_telemetry\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rpm\" or r[\"_field\"] == \"is_anomaly\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r[\"is_anomaly\"] == 1)\r\n  |> keep(columns: [\"_time\", \"rpm\"])\r\n  |> rename(columns: {rpm: \"_value\"})\r\n  |> set(key: \"_field\", value: \"anomaly_rpm\")"
    }
   ]
  },
  {
   "title": "Pedal inputs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"car_telemetry\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"throttle\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"car_telemetry\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"brake\")\r\n  |> toFloat()\r\n  |> map(fn: (r) => ({r with _value: r._value * -100.0}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"car_telemetry\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"throttle\" or r[\"_field\"] == \"is_anomaly\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r[\"is_anomaly\"] == 1)\r\n  |> keep(columns: [\"_time\", \"throttle\"])\r\n  |> rename(columns: {throttle: \"_value\"})\r\n  |> set(key: \"_field\", value: \"anomaly_throttle\")"
    },
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"car_telemetry\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"brake\" or r[\"_field\"] == \"is_anomaly\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r[\"is_anomaly\"] == 1)\r\n  |> keep(columns: [\"_time\", \"brake\"])\r\n  |> rename(columns: {brake: \"_value\"})\r\n  |> set(key: \"_field\", value: \"anomaly_brake\")"
    }
   ]
  },
  {
   "title": "Gears",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"car_telemetry\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gear\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"car_telemetry\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gear\" or r[\"_field\"] == \"is_anomaly\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r[\"is_anomaly\"] == 1)\r\n  |> keep(columns: [\"_time\", \"gear\"])\r\n  |> rename(columns: {gear: \"_value\"})\r\n  |> set(key: \"_field\", value: \"anomaly_gear\")"
    }
   ]
  }
 ]
}